# Build step
FROM node:20-alpine as build

WORKDIR /app

COPY . .

RUN npm install
RUN npm run build --prod

# Serve step
FROM nginx:alpine

# Copy build output to nginx public folder
COPY --from=build /app/dist/task-manager /usr/share/nginx/html

# Copy your custom nginx.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
