name: FastAPI Backend CI/CD

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-fastapi-app:latest

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Update docker-compose.yml to use pushed image
        run: |
          sed -i 's|build: ./backend|image: ${{ secrets.DOCKER_USERNAME }}/my-fastapi-app:latest|' backend/docker-compose.yml

      - name: Run Docker Compose stack
        working-directory: backend
        run: |
          docker-compose up -d
          sleep 20  # wait for services to be ready
          docker-compose ps

      - name: Run tests inside backend container
        working-directory: backend
        run: |
          docker-compose exec backend pytest

      - name: Shutdown Docker Compose
        working-directory: backend
        run: |
          docker-compose down
